apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devapp2
  labels:
    app: devapp2
  name: devapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devapp2
  template:
    metadata:
      labels:
        app: devapp2
    spec:
      containers:
      - image: nginx:1.25.1
        name: devapp2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
