apiVersion: v1
kind: Service
metadata:
  namespace: devapp1
  labels:
    app: devapp1
  name: devapp1
spec:
  selector:
    app: devapp1
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
